#!/usr/bin/env bash
# script that displays information about subdomains
function audit_subdomain {
    local domain=$1
    local subdomain=$2

    if [ -z "$subdomain" ]; then
        subdomains=("www" "lb-01" "web-01" "web-02")
    else
        subdomains=("$subdomain")
    fi

    for sub in "${subdomains[@]}"; do
        record_type=$(dig +short "$sub"."$domain" | awk '{print $4}')
        destination=$(dig +short "$sub"."$domain" | awk '{print $1}')
        echo "The subdomain $sub is a $record_type record and points to $destination"
    done
}

audit_subdomain "$1" "$2"
