#!/usr/bin/env bash
##########################################################
# Script: MySQL Backup and Compression
# Description: This script performs a MySQL database backup and compresses it into a tar.gz archive.
##########################################################


# Check if password is supplied
if [ $# -ne 1 ]; then
    echo "Usage: $0 <mysql root password>"
    exit 1
fi

# MySQL root password
password="$1"

# Get current date
current_date=$(date +%d-%m-%Y)

# MySQL dump filename
dump_file="backup.sql"

# Archive filename
archive_file="${current_date}.tar.gz"

# Dump all databases to backup.sql
mysqldump -u root -p$password --all-databases > "$dump_file"

# Compress the dump file into a tar.gz archive
tar -czvf "$archive_file" "$dump_file"

# Remove the dump file
rm "$dump_file"

# Rename the dump file to backup.sql
mv "$archive_file" "backup.sql"

echo "Backup successfully created and compressed: backup.sql"
