#!/usr/bin/env bash

# Check if user has root privileges
if [[ $EUID -ne 0 ]]; then
   echo "This script must be run as root" 
   exit 1
fi

# Display header
echo "Listening Ports - PID - Program"

# Use netstat to list listening sockets, filter by 'LISTEN' state
netstat -tuln | awk '$6 == "LISTEN" {print $4, $7}' | while read line; do
    port=$(echo "$line" | awk '{print $1}')
    pid=$(echo "$line" | awk -F '/' '{print $1}')
    program=$(echo "$line" | awk -F '/' '{print $2}')
    if [[ $pid =~ ^[0-9]+$ ]]; then
        program=$(ps -p $pid -o comm=)
    fi
    echo "$port - $pid - $program"
done

