#!/usr/bin/env bash
# Configure Nginx to listen on port 80 of all active IPv4 IPs
sudo apt-get update
sudo apt-get install nginx
sudo sed -i 's/listen \[::\]:80 default_server;/listen 80 default_server;/g' /etc/nginx/sites-available/default
sed -i "s/listen \[::\]:8080 default_server ipv6only=on;/listen \[::\]:80 default_server;/" /etc/nginx/sites-enabled/default
sed -i "s/ ipv6only=on//" /etc/nginx/sites-available/default
sudo systemctl restart nginx
