#!/usr/bin/env bash
# Configure Nginx to listen on port 80 of all active IPv4 IPs
sudo sed -i 's/listen \[::\]:80 default_server;/listen 80 default_server;/g' /etc/nginx/sites-available/default
sudo systemctl restart nginx